;; generated by paraphrase, uses esrap

(IN-PACKAGE :peg-grammar)

(ESRAP:DEFRULE pg:GRAMMAR (AND pg:SPACING (esrap:+ pg:DEFINITION) pg:SPACING pg:ENDOFFILE)
  (:DESTRUCTURE
   (pg:SPC pg:DEF pg:SPC2 pg:EOF)
   (DECLARE (IGNORE pg:SPC pg:EOF pg:SPC2))
   `(PROGN ,@pg:DEF)))

(ESRAP:DEFRULE pg:DEFINITION
               (AND pg:IDENTIFIER
                    pg:LEFTARROW
                    pg:EXPRESSION
                    pg:SPACING
                    (ESRAP:? pg:SEMANTICCODE))
  (:DESTRUCTURE
   (pg:ID pg:ARR pg:E pg:SPC pg:CODE)
   (DECLARE (IGNORE pg:ARR pg:SPC))
   (IF (NULL pg:CODE)
       `(ESRAP:DEFRULE ,(INTERN (STRING-UPCASE pg:ID)) ,pg:E)
     `(ESRAP:DEFRULE ,(INTERN (STRING-UPCASE pg:ID)) ,pg:E ,pg:CODE))))

(ESRAP:DEFRULE pg:SEMANTICCODE (AND pg:OPENBRACE (esrap:+ pg:NOTBRACE) pg:CLOSEBRACE)
  (:DESTRUCTURE
   (pg:LB pg:CODE pg:RB)
   (DECLARE (IGNORE pg:LB pg:RB))
   (READ-FROM-STRING (esrap:TEXT pg:CODE))))

(ESRAP:DEFRULE pg:NOTBRACE (OR pg:UQLITERAL (AND (ESRAP:! "}") pg:CHARACTER))
  (:TEXT pg:T))

(ESRAP:DEFRULE pg:EXPRESSION (AND pg:PSEQUENCE (esrap:* pg:SLASHSEQUENCE))
  (:DESTRUCTURE (pg:SEQ pg:SEQS) (IF pg:SEQS `(OR ,pg:SEQ ,@pg:SEQS) pg:SEQ)))

(ESRAP:DEFRULE pg:SLASHSEQUENCE (AND pg:SLASH pg:PSEQUENCE)
  (:DESTRUCTURE (SL SEQ) (DECLARE (IGNORE SL)) SEQ))

(ESRAP:DEFRULE pg:PSEQUENCE (esrap:* pg:PREFIX)
  (:DESTRUCTURE
   (&REST pg:PREF)
   (IF pg:PREF
       (IF (AND (CONSP pg:PREF) (> (LENGTH pg:PREF) 1))
           `(AND ,@pg:PREF)
         (FIRST pg:PREF))
     (VALUES))))

(ESRAP:DEFRULE pg:PREFIX (AND (ESRAP:? (OR pg:PAND pg:PNOT)) pg:SUFFIX)
  (:DESTRUCTURE (pg:PREF pg:SUFF) (IF pg:PREF (LIST pg:PREF pg:SUFF) pg:SUFF)))

(ESRAP:DEFRULE pg:SUFFIX (AND pg:PRIMARY (ESRAP:? (OR pg:QUESTION pg:STAR pg:PLUS)))
  (:DESTRUCTURE (pg:PRIM pg:SUFF) (IF pg:SUFF (LIST pg:SUFF pg:PRIM) pg:PRIM)))

(ESRAP:DEFRULE pg:PRIMARY (OR pg:P1 pg:P2 pg:LITERAL pg:PCLASS pg:DOT) (:LAMBDA (pg:X) pg:X))

(ESRAP:DEFRULE pg:P1 (AND pg:IDENTIFIER (ESRAP:! pg:LEFTARROW))
  (:FUNCTION FIRST))

(ESRAP:DEFRULE pg:P2 (AND pg:OPENPAREN pg:EXPRESSION pg:CLOSEPAREN)
  (:FUNCTION SECOND))

(ESRAP:DEFRULE pg:IDENTIFIER pg:STRINGIDENTIFIER
  (:LAMBDA (pg:X) (INTERN (STRING-UPCASE pg:X))))

(ESRAP:DEFRULE pg:STRINGIDENTIFIER (AND pg:IDENTSTART (esrap:* pg:IDENTCONT) pg:SPACING)
  (:TEXT pg:T))

(ESRAP:DEFRULE pg:IDENTSTART
               (ESRAP:CHARACTER-RANGES (#\a #\z) (#\A #\Z) #\_))

(ESRAP:DEFRULE pg:IDENTCONT
               (OR pg:IDENTSTART "-" (ESRAP:CHARACTER-RANGES (#\0 #\9))))

(ESRAP:DEFRULE pg:LITERAL
               (OR (AND (ESRAP:CHARACTER-RANGES #\')
                        (esrap:* pg:NOTSINGLE)
                        (ESRAP:CHARACTER-RANGES #\')
                        pg:SPACING)
                   (AND (ESRAP:CHARACTER-RANGES #\")
                        (esrap:* NOTDOUBLE)
                        (ESRAP:CHARACTER-RANGES #\")
                        PG:SPACING))
  (:DESTRUCTURE
   (pg:Q1 pg:STRING pg:Q2 pg:SPC)
   (DECLARE (IGNORE pg:Q1 pg:Q2 pg:SPC))
   (TEXT pg:STRING)))

(ESRAP:DEFRULE pg:UQLITERAL
               (AND (ESRAP:CHARACTER-RANGES #\")
                    (esrap:* NOTDOUBLE)
                    (ESRAP:CHARACTER-RANGES #\")
                    PG:SPACING)
  (:DESTRUCTURE
   (pg:Q1 pg:STRING pg:Q2 pg:SPC)
   (DECLARE (IGNORE pg:SPC))
   `(,pg:Q1 ,@pg:STRING ,pg:Q2)))

(ESRAP:DEFRULE pg:NOTSINGLE
               (AND (ESRAP:! (ESRAP:CHARACTER-RANGES #\')) pg:PCHAR)
  (:FUNCTION SECOND))

(ESRAP:DEFRULE pg:NOTDOUBLE
               (AND (ESRAP:! (ESRAP:CHARACTER-RANGES #\")) pg:PCHAR)
  (:FUNCTION SECOND))

(ESRAP:DEFRULE pg:PCLASS (AND "[" (esrap:* NOTRB) "]" PG:SPACING)
  (:DESTRUCTURE
   (pg:LB pg:RANGE pg:RB pg:SPC)
   (DECLARE (IGNORE pg:LB pg:RB pg:SPC))
   (IF (AND (CONSP pg:RANGE)
            (OR (NOT (= 2 (LENGTH pg:RANGE)))
                (OR (CONSP (FIRST pg:RANGE)) (CONSP (SECOND pg:RANGE)))))
       `(CHARACTER-RANGES ,@pg:RANGE)
     `(CHARACTER-RANGES ,pg:RANGE))))

(ESRAP:DEFRULE pg:NOTRB (AND (ESRAP:! "]") pg:RANGE) (:FUNCTION SECOND))

(ESRAP:DEFRULE pg:RANGE (OR pg:CHARRANGE pg:SINGLECHAR))

(ESRAP:DEFRULE pg:CHARRANGE (AND pg:PCHAR "-" pg:PCHAR)
  (:DESTRUCTURE (pg:C1 pg:DASH pg:C2) (DECLARE (IGNORE pg:DASH)) (LIST pg:C1 pg:C2)))

(ESRAP:DEFRULE SINGLECHAR pg:PCHAR (:LAMBDA (pg:C) pg:C))

(ESRAP:DEFRULE pg:PCHAR (OR pg:ESCCHAR pg:NUMCHAR1 pg:NUMCHAR2 pg:ANYCHAR))

(ESRAP:DEFRULE pg:ESCCHAR
               (AND "\\"
                    (OR "n"
                        "r"
                        "t"
                        (ESRAP:CHARACTER-RANGES #\')
                        "\""
                        "["
                        "]"
                        "\\"
                        "{"
                        "}"))
  (:DESTRUCTURE
   (pg:SL pg:CH)
   (DECLARE (IGNORE pg:SL))
   (LET ((pg:C (OR (AND (CHARACTERP pg:CH) pg:CH) (CHAR pg:CH 0))))
     (CASE pg:C
       (#\n #\Newline)
       (#\r #\Return)
       (#\t #\Tab)
       (OTHERWISE pg:C)))))

(ESRAP:DEFRULE pg:NUMCHAR1
               (AND "\\"
                    (ESRAP:CHARACTER-RANGES (#\0 #\2))
                    (ESRAP:CHARACTER-RANGES (#\0 #\7))
                    (ESRAP:CHARACTER-RANGES (#\0 #\7)))
  (:DESTRUCTURE
   (pg:SL pg:N1 pg:N2 pg:N3)
   (DECLARE (IGNORE pg:SL))
   (CODE-CHAR (PARSE-INTEGER (CONCATENATE 'STRING pg:N1 pg:N2 pg:N3) :RADIX 8))))

(ESRAP:DEFRULE pg:NUMCHAR2
               (AND "\\"
                    (ESRAP:CHARACTER-RANGES (#\0 #\7))
                    (ESRAP:? (ESRAP:CHARACTER-RANGES (#\0 #\7))))
  (:DESTRUCTURE
   (pg:SL pg:N1 pg:N2)
   (DECLARE (IGNORE pg:SL))
   (CODE-CHAR (PARSE-INTEGER (CONCATENATE 'STRING pg:N1 pg:N2) :RADIX 8))))

(ESRAP:DEFRULE pg:ANYCHAR (AND (ESRAP:! "\\") pg:CHARACTER)
  (:DESTRUCTURE (pg:SL pg:C) (DECLARE (IGNORE pg:SL)) pg:C))

(ESRAP:DEFRULE LEFTARROW (AND "<-" PG:SPACING)
  (:LAMBDA (pg:LIST) (DECLARE (IGNORE pg:LIST)) (VALUES)))

(ESRAP:DEFRULE pg:SLASH (AND "/" PG:SPACING)
  (:LAMBDA (pg:LIST) (DECLARE (IGNORE pg:LIST)) (VALUES)))

(ESRAP:DEFRULE pg:PAND (AND "&" PG:SPACING)
  (:LAMBDA (pg:LIST) (DECLARE (IGNORE pg:LIST)) 'AND))

(ESRAP:DEFRULE pg:PNOT (AND "!" PG:SPACING)
  (:LAMBDA (pg:LIST) (DECLARE (IGNORE pg:LIST)) 'esrap:!))

(ESRAP:DEFRULE pg:QUESTION (AND "?" PG:SPACING)
  (:LAMBDA (pg:LIST) (DECLARE (IGNORE pg:LIST)) 'esrap:?))

(ESRAP:DEFRULE pg:STAR (AND "*" PG:SPACING)
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) 'esrap:*))

(ESRAP:DEFRULE pg:PLUS (AND "+" PG:SPACING)
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) 'esrap:+))

(ESRAP:DEFRULE PG:OPENPAREN (AND "(" PG:SPACING)
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) (VALUES)))

(ESRAP:DEFRULE PG:CLOSEPAREN (AND ")" PG:SPACING)
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) (VALUES)))

(ESRAP:DEFRULE PG:OPENBRACE (AND "{" PG:SPACING)
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) (VALUES)))

(ESRAP:DEFRULE PG:CLOSEBRACE (AND "}" PG:SPACING)
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) (VALUES)))

(ESRAP:DEFRULE PG:DOT (AND "." PG:SPACING)
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) 'pg:CHARACTER))

(ESRAP:DEFRULE PG:PG:SPACING (esrap:* (OR pg:PSPACE pg:COMMENT))
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) (VALUES)))

(ESRAP:DEFRULE PG:COMMENT
               (AND "#"
                    (esrap:* (AND (ESRAP:! pg:ENDOFLINE) pg:CHAR1))
                    (OR pg:ENDOFLINE pg:ENDOFFILE))
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) (VALUES)))

(ESRAP:DEFRULE PG:CHAR1 CHARACTER (:LAMBDA (pg:C) pg:C))

(ESRAP:DEFRULE PG:PSPACE (OR " " "	" pg:ENDOFLINE)
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) (VALUES)))

(ESRAP:DEFRULE PG:ENDOFLINE
               (OR "
"
                   "
"
                   "")
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) (VALUES)))

(ESRAP:DEFRULE PG:ENDOFFILE (ESRAP:! CHARACTER)
  (:LAMBDA (PG:LIST) (DECLARE (IGNORE PG:LIST)) (VALUES)))
